apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-restaurant
  namespace: restaurant
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/healthcheck-path: '/actuator/health/readiness'
    #alb.ingress.kubernetes.io/group.name: my-restaurant
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: 226796600291.realhandsonlabs.net

spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: restaurant
                port:
                  number: 80
      host: restaurant.226796600291.realhandsonlabs.net
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-order
  namespace: order
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/healthcheck-path: '/actuator/health/readiness'
    #alb.ingress.kubernetes.io/group.name: my-restaurant
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: 226796600291.realhandsonlabs.net

spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: order
                port:
                  number: 80
      host: order.226796600291.realhandsonlabs.net
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: nginx
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/healthcheck-path: '/'
    #alb.ingress.kubernetes.io/group.name: my-restaurant
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: 226796600291.realhandsonlabs.net


spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: nginx
                port:
                  number: 80
      host: nginx.226796600291.realhandsonlabs.net
---
